package com.playtranslate.ocr.core

import android.graphics.PointF
import android.graphics.Rect
import com.playtranslate.language.TextOrientation
import kotlin.math.abs
import kotlin.math.cos
import kotlin.math.roundToInt
import kotlin.math.sin
import kotlin.random.Random
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner

/**
 * [OrientedBoxGeometry] policy tests. Quads are generated by rotating a W×H
 * rect about its center, so the expected angle/dims are known exactly. Boundary
 * angles avoid the exact thresholds (10°, 60°) by a safe margin — the recovered
 * angle carries float error, and the policy's job at the threshold is only that
 * SOME side wins, not which ulp.
 */
@RunWith(RobolectricTestRunner::class)
class OrientedBoxGeometryTest {

    /** TL,TR,BR,BL corners of a w×h rect centered at (cx,cy), rotated by [deg]
     *  clockwise (y-down screen coords). */
    private fun quad(w: Float, h: Float, deg: Float, cx: Float = 500f, cy: Float = 500f): List<PointF> {
        val r = Math.toRadians(deg.toDouble())
        val c = cos(r).toFloat(); val s = sin(r).toFloat()
        return listOf(
            PointF(-w / 2, -h / 2), PointF(w / 2, -h / 2),
            PointF(w / 2, h / 2), PointF(-w / 2, h / 2),
        ).map { PointF(cx + it.x * c - it.y * s, cy + it.x * s + it.y * c) }
    }

    private fun aabbOf(q: List<PointF>) = Rect(
        q.minOf { it.x }.roundToInt(), q.minOf { it.y }.roundToInt(),
        q.maxOf { it.x }.roundToInt(), q.maxOf { it.y }.roundToInt(),
    )

    private fun boxAt(deg: Float, w: Float = 200f, h: Float = 40f): OcrBox {
        val q = quad(w, h, deg)
        return OrientedBoxGeometry.boxFor(aabbOf(q), q, TextOrientation.HORIZONTAL)
    }

    // ── fromQuad: angle + dims recovery ──────────────────────────────────────

    @Test
    fun `recovers angle and dims across the band, both signs`() {
        for (deg in floatArrayOf(12f, 15f, 30f, 44f, 46f, 50f, 59f, 75f)) {
            for (sign in floatArrayOf(1f, -1f)) {
                val theta = deg * sign
                val o = OrientedBoxGeometry.fromQuad(quad(200f, 40f, theta))!!
                assertEquals("angle at $theta", theta, o.angleDeg, 0.5f)
                assertEquals("long at $theta", 200f, o.longSide, 1f)
                assertEquals("short at $theta", 40f, o.shortSide, 1f)
            }
        }
    }

    @Test
    fun `axis-aligned and near-axis quads read as near zero`() {
        for (deg in floatArrayOf(0f, 5f, -5f, 9.5f, -9.5f)) {
            val o = OrientedBoxGeometry.fromQuad(quad(200f, 40f, deg))!!
            assertEquals(deg, o.angleDeg, 0.5f)
        }
    }

    @Test
    fun `continuous through 45 degrees`() {
        val below = OrientedBoxGeometry.fromQuad(quad(200f, 40f, 44.5f))!!
        val above = OrientedBoxGeometry.fromQuad(quad(200f, 40f, 45.5f))!!
        assertTrue(
            "angle jumped across 45°: ${below.angleDeg} -> ${above.angleDeg}",
            abs(above.angleDeg - below.angleDeg) < 2f,
        )
        // Exactly 45° may tie the corner heuristic (→ null, refused) or resolve
        // by float ulps (→ ~±45°); either is acceptable, a −45 flip is not.
        OrientedBoxGeometry.fromQuad(quad(200f, 40f, 45f))?.let {
            assertEquals(45f, abs(it.angleDeg), 1f)
        }
    }

    @Test
    fun `corner order and winding do not matter`() {
        val base = quad(200f, 40f, 25f)
        val expect = OrientedBoxGeometry.fromQuad(base)!!
        val variants = (0..3).map { shift -> List(4) { base[(it + shift) % 4] } } +
            listOf(base.reversed())
        for (v in variants) {
            val o = OrientedBoxGeometry.fromQuad(v)!!
            assertEquals(expect.angleDeg, o.angleDeg, 0.01f)
            assertEquals(expect.longSide, o.longSide, 0.01f)
            assertEquals(expect.shortSide, o.shortSide, 0.01f)
        }
    }

    @Test
    fun `degenerate quads are refused`() {
        val p = PointF(10f, 10f)
        assertEquals(null, OrientedBoxGeometry.fromQuad(listOf(p, p, p, p)))
        assertEquals(null, OrientedBoxGeometry.fromQuad(quad(200f, 40f, 20f).take(3)))
    }

    // ── boxFor: the policy ladder ────────────────────────────────────────────

    @Test
    fun `band interior produces a rotated box with the aabb as bounds`() {
        val q = quad(200f, 40f, 30f)
        val aabb = aabbOf(q)
        val box = OrientedBoxGeometry.boxFor(aabb, q, TextOrientation.HORIZONTAL)
        assertTrue(box.isRotated)
        assertEquals(30f, box.angleDeg, 0.5f)
        assertEquals(200f, box.orientedWidth, 1f)
        assertEquals(40f, box.orientedHeight, 1f)
        assertEquals(aabb, box.bounds)
    }

    @Test
    fun `snap zone and band ceiling fall back to upright`() {
        // The two-term gate (post threshold-drop): |θ| ≤ 3° snaps at any
        // length; the band ceiling still snaps; between them the corner
        // excursion (ow/2)·sin|θ| decides — a 200px line at 5° sweeps ~8.7px
        // (real slant, carried) while the same angle on a 60px line sweeps
        // ~2.6px (short-line noise, snapped).
        for (deg in floatArrayOf(0f, 2.9f, -2.9f, 61f, -61f, 75f, 90f)) {
            val box = boxAt(deg)
            assertEquals("angle $deg should be upright", 0f, box.angleDeg, 0f)
        }
        for (deg in floatArrayOf(5f, -5f, 10.6f, -10.6f, 59f, -59f)) {
            assertTrue("angle $deg should be rotated at 200px", boxAt(deg).isRotated)
        }
        for (deg in floatArrayOf(5f, -5f, 10.6f, -10.6f)) {
            assertEquals(
                "angle $deg on a 60px line is sub-excursion noise",
                0f, boxAt(deg, w = 60f, h = 20f).angleDeg, 0f,
            )
        }
    }

    @Test
    fun `unmeasured bit marks withheld angles never measurements`() {
        // Sub-excursion snap: there WAS a reading, but too short to trust —
        // the angle is WITHHELD, and grouping may re-place the box by
        // position.
        assertTrue(boxAt(5f, w = 60f, h = 20f).angleUnmeasured)
        // Near-square: the axis direction itself is unreliable — withheld.
        assertTrue(boxAt(20f, w = 44f, h = 40f).angleUnmeasured)
        // Measurements and engine assertions are NOT withheld: a carried
        // slant, a sub-3° snap (measured straight), and the upright factory.
        assertFalse(boxAt(5f).angleUnmeasured)
        assertFalse(boxAt(2f).angleUnmeasured)
        assertFalse(OcrBox.upright(Rect(0, 0, 100, 20)).angleUnmeasured)
        // Invariant: an unmeasured box is always angle-0.
        assertEquals(0f, boxAt(5f, w = 60f, h = 20f).angleDeg, 0f)
    }

    @Test
    fun `vertical orientation zeroes the angle - tategaki is not rotation`() {
        // A tall column, upright and slanted: both must come back upright.
        for (deg in floatArrayOf(0f, 15f)) {
            val q = quad(40f, 300f, deg)
            val box = OrientedBoxGeometry.boxFor(aabbOf(q), q, TextOrientation.VERTICAL)
            assertEquals(0f, box.angleDeg, 0f)
            assertEquals(OcrBox.upright(aabbOf(q)), box)
        }
    }

    @Test
    fun `near-square quads have no trusted axis`() {
        val q = quad(50f, 45f, 30f)
        assertEquals(0f, OrientedBoxGeometry.boxFor(aabbOf(q), q, TextOrientation.HORIZONTAL).angleDeg, 0f)
    }

    @Test
    fun `missing or malformed quads fall back to upright`() {
        val aabb = Rect(0, 0, 100, 30)
        assertEquals(OcrBox.upright(aabb), OrientedBoxGeometry.boxFor(aabb, null, TextOrientation.HORIZONTAL))
        assertEquals(
            OcrBox.upright(aabb),
            OrientedBoxGeometry.boxFor(aabb, quad(200f, 40f, 20f).take(3), TextOrientation.HORIZONTAL),
        )
    }

    @Test
    fun `paddle band ceiling - maxSlantDeg 45 clamps the flip zone`() {
        // The Paddle producer passes maxSlantDeg = 45f: past 45° DbNet's corner
        // ordering rolls and warpCrop treats elongated quads as columns, so no
        // angle is claimed there (Codex adversarial finding, option A). Pin
        // both sides of the boundary, and that the default band is unaffected.
        for (sign in floatArrayOf(1f, -1f)) {
            val fifty = quad(200f, 40f, 50f * sign)
            val clamped = OrientedBoxGeometry.boxFor(
                aabbOf(fifty), fifty, TextOrientation.HORIZONTAL, maxSlantDeg = 45f,
            )
            assertEquals("50° must clamp under the Paddle band", OcrBox.upright(aabbOf(fifty)), clamped)

            val fortyFour = quad(200f, 40f, 44f * sign)
            val kept = OrientedBoxGeometry.boxFor(
                aabbOf(fortyFour), fortyFour, TextOrientation.HORIZONTAL, maxSlantDeg = 45f,
            )
            assertTrue("44° stays rotated under the Paddle band", kept.isRotated)

            val defaultBand = OrientedBoxGeometry.boxFor(
                aabbOf(fifty), fifty, TextOrientation.HORIZONTAL,
            )
            assertTrue("50° stays rotated under the default (ML Kit) band", defaultBand.isRotated)
        }
    }

    @Test
    fun `producer invariant - nonzero angle iff isRotated`() {
        val rnd = Random(42)
        repeat(300) {
            val w = 20f + rnd.nextFloat() * 400f
            val h = 10f + rnd.nextFloat() * 100f
            val deg = -90f + rnd.nextFloat() * 180f
            val q = quad(w, h, deg, cx = rnd.nextFloat() * 2000f, cy = rnd.nextFloat() * 2000f)
            val box = OrientedBoxGeometry.boxFor(aabbOf(q), q, TextOrientation.HORIZONTAL)
            assertEquals("w=$w h=$h deg=$deg", box.angleDeg != 0f, box.isRotated)
        }
    }
}
